# -*- coding: utf-8 -*-
"""GuncelKonularProje.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UOcMQB8-60V5uRASOyJozVZFXa_jNpwq
"""

from google.colab import drive
drive.mount('/content/drive')

#Kütüphanelerin Yüklenmesi

import pandas as pd
import numpy as np

veri_universite = pd.read_excel("/content/drive/My Drive/GuncelKonular/veriler/universite.xlsx")
veri_bursa = pd.read_excel("/content/drive/My Drive/GuncelKonular/veriler/bursa.xlsx")
veri_beyazid = pd.read_excel("/content/drive/My Drive/GuncelKonular/veriler/beyazid.xlsx")
veri_inegol = pd.read_excel("/content/drive/My Drive/GuncelKonular/veriler/inegol.xlsx")
veri_kestel = pd.read_excel("/content/drive/My Drive/GuncelKonular/veriler/kestel.xlsx")
veri_kulturpark = pd.read_excel("/content/drive/My Drive/GuncelKonular/veriler/kulturpark.xlsx")



def calculateSO2(so2):
    so2veri=0
    if (so2>=0.0 and so2<=4.0):
         so2veri= 1.0
    if (so2>4.0 and so2<=8.0):
         so2veri= 2.0
    if (so2>8.0 and so2<=38.0):
         so2veri= 3.0
    if (so2>38.0 and so2<=80.0):
         so2veri= 4.0
    if (so2>80.0 and so2<=160.0):
         so2veri= 5.0
    if (so2>160.0):
         so2veri= 6.0
    
    return so2veri

def calculateNo2(no2):
    no2veri=0
    if (no2>=0 and so2<=40):
         no2veri= 1.0
    if (no2>40 and no2<=80):
         no2veri= 2.0
    if (no2>80 and no2<=180):
         no2veri= 3.0
    if (no2>180 and no2<=280):
         no2veri= 4.0
    if (no2>280 and no2<=400):
         no2veri= 5.0
    if (no2>400):
         no2veri= 6.0
    return no2veri

def calculatePM10(pm10):
    pm10veri=0
    if (pm10>=0 and pm10<=50):
         pm10veri= 1.0
    if (pm10>=51 and pm10<=100):
         pm10veri= 2.0
    if (pm10>=101 and pm10<=250):
         pm10veri= 3.0
    if (pm10>=251 and pm10<=350):
         pm10veri= 4.0
    if (pm10>=351 and pm10<=430):
         pm10veri= 5.0
    if (pm10>=431):
         pm10veri= 6.0
    
    return pm10veri

def calculatePM25(pm25):
    pm25veri=0
    if (pm25>=0 and pm25<=30):
         pm25veri= 1.0
    if (pm25>=31 and pm25<=60):
         pm25veri= 2.0
    if (pm25>=61 and pm25<=90):
         pm25veri= 3.0
    if (pm25>=91 and pm25<=120):
         pm25veri= 4.0
    if (pm25>=121 and pm25<=250):
         pm25veri= 5.0
    if (pm25>=251):
         pm25veri= 6.0
    
    return pm25veri

def calculateCO(CO):
    coveri=0
    if (CO>=0 and CO<=5500):
         coveri= 1.0
    if (CO>=5501 and CO<=10000):
         coveri= 2.0
    if (CO>=10001 and CO<=16000):
         coveri= 3.0
    if (CO>=16001 and CO<=24000):
         coveri= 4.0
    if (CO>=24001 and CO<=32000):
         coveri= 5.0
    if (CO>=32001 and CO<=40000):
         coveri= 6.0
    return coveri

def calculateO3(O3):
    o3veri=0
    if (O3>=0 and O3<=50):
         o3veri= 1.0
    if (O3>50 and O3<=100):
         o3veri= 2.0
    if (O3>=100 and O3<=168):
         o3veri= 3.0
    if (O3>168 and O3<=208):
         o3veri= 4.0
    if (O3>208 and O3<=748):
         o3veri= 5.0
    if (O3>748):
         o3veri= 6.0
    return o3veri

def pm10Hesapla(df):
  for pm10 in df["PM25"]:
    df["PM10"] = df["PM25"] / 0.75
  return df

def pm25Hesapla(df):
  for pm25 in df["PM10"]:
    df["PM25"] = df["PM10"] * 0.75
  return df

def dropNOandDate(df):
  df = df.drop(["Tarih","NO"], axis=1)
  return df

def dropDate(df):
  df = df.drop(["Tarih"], axis=1)
  return df

Bolgeler = ["universite","kulturpark","kestel","inegol","bursa","beyazid"]
bolge_pd_listeleri = [veri_universite,veri_kulturpark,veri_kestel,veri_inegol,veri_bursa,veri_beyazid]

# # Üniversite
# df_universite = bolge_pd_listeleri[0]
# df_universite = dropNOandDate(df_universite)
# # Kültürpark
# df_kulturpark = bolge_pd_listeleri[1]
# df_kulturpark = dropNOandDate(df_kulturpark)
# # Kestel
# df_kestel = bolge_pd_listeleri[2]
# df_kestel = dropNOandDate(df_kestel)
# # inegol
# df_inegol = bolge_pd_listeleri[3]
# df_inegol = dropNOandDate(df_inegol)
# # bursa
# df_bursa = bolge_pd_listeleri[4]
# df_bursa = dropDate(df_bursa)
# # bursa
# df_beyazid = bolge_pd_listeleri[5]
# df_beyazid = dropNOandDate(df_beyazid)

# df_beyazid.to_excel("/content/drive/My Drive/GuncelKonular/guncel/beyazid.xlsx")
# df_bursa.to_excel("/content/drive/My Drive/GuncelKonular/guncel/bursa.xlsx")
# df_inegol.to_excel("/content/drive/My Drive/GuncelKonular/guncel/inegol.xlsx")
# df_kestel.to_excel("/content/drive/My Drive/GuncelKonular/guncel/kestel.xlsx")
# df_kulturpark.to_excel("/content/drive/My Drive/GuncelKonular/guncel/kulturpark.xlsx")
# df_universite.to_excel("/content/drive/My Drive/GuncelKonular/guncel/universite.xlsx")

# df_universite = pm10Hesapla(df_universite)
# df_kestel = pm25Hesapla(df_kestel)
# df_inegol = pm25Hesapla(df_inegol)
# df_beyazid = pm25Hesapla(df_beyazid)

# df_universite["CO"] = df_beyazid["CO"]
# df_kulturpark["CO"] = df_beyazid["CO"]
# df_kulturpark["PM25"] = df_beyazid["PM25"]
# df_kulturpark["PM10"] = df_beyazid["PM10"]
# df_kestel["CO"] = df_beyazid["CO"]
# df_inegol["CO"] = df_kestel["CO"]
# df_inegol["O3"] = df_kestel["O3"]
# df_bursa["CO"] = df_kulturpark["CO"]
# df_bursa["NO2"] = df_kulturpark["NO2"]
# df_beyazid["O3"] = df_kulturpark["O3"]

# data_beyazid = pd.DataFrame()

def hesapla(df):
  data = pd.DataFrame()
  for so2 in df["SO2"]:
      data["SO2"] = df["SO2"].apply(calculateSO2)
  for no2 in df["NO2"]:
      data["NO2"] = df["NO2"].apply(calculateNo2)
  for o3 in df["O3"]:
      data["O3"] = df["O3"].apply(calculateO3)
  for pm25 in df["PM25"]:
      data["PM25"] = df["PM25"].apply(calculatePM25)
  for pm10 in df["PM10"]:
      data["PM10"] = df["PM10"].apply(calculatePM10)
  for co in df["CO"]:
      data["CO"] = df["CO"].apply(calculateCO)
  return data

data_beyazid = hesapla(df_beyazid)
data_beyazid.head()

data_universite = hesapla(df_universite)
data_universite.head()

data_kulturpark = hesapla(df_kulturpark)
data_kulturpark.head()

data_kestel = hesapla(df_kestel)
data_kestel.head()

data_inegol = hesapla(df_inegol)
data_inegol.head()

data_bursa = hesapla(df_bursa)
data_bursa.head()

# data_beyazid.to_excel("/content/drive/My Drive/GuncelKonular/data_veri/data_beyazid.xlsx")
# data_bursa.to_excel("/content/drive/My Drive/GuncelKonular/data_veri/data_bursa.xlsx")
# data_inegol.to_excel("/content/drive/My Drive/GuncelKonular/data_veri/data_inegol.xlsx")
# data_kestel.to_excel("/content/drive/My Drive/GuncelKonular/data_veri/data_kestel.xlsx")
# data_kulturpark.to_excel("/content/drive/My Drive/GuncelKonular/data_veri/data_kulturpark.xlsx")
# data_universite.to_excel("/content/drive/My Drive/GuncelKonular/data_veri/data_universite.xlsx")

data_beyazid.head(10)
yeni_beyazid = pd.DataFrame()

# data_beyazid["toplam"] = data_beyazid.sum(axis=1)
data_bursa["toplam"] = data_bursa.sum(axis=1)
data_inegol["toplam"] = data_inegol.sum(axis=1)
data_kestel["toplam"] = data_kestel.sum(axis=1)
data_kulturpark["toplam"] = data_kulturpark.sum(axis=1)
data_universite["toplam"] = data_universite.sum(axis=1)

data_universite.head()

kalite_olcutu = ["Çok iyi", "Güzel","Orta","Kötü","Çok Kötü","Ölümcül"]

# data_beyazid = sonucCikart(data_beyazid)
# data_bursa = sonucCikart(data_bursa)
# data_inegol = sonucCikart(data_inegol)
# data_kestel = sonucCikart(data_kestel)
# data_kulturpark = sonucCikart(data_kulturpark)
# data_universite = sonucCikart(data_universite)

# data_beyazid.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar/data_beyazid.xlsx")
# data_bursa.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar/data_bursa.xlsx")
# data_inegol.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar/data_inegol.xlsx")
# data_kestel.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar/data_kestel.xlsx")
# data_kulturpark.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar/data_kulturpark.xlsx")
# data_universite.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar/data_universite.xlsx")

def kaliteHesabi2(toplam):
    hesap= ""
    if (toplam>=0.0 and toplam<=6.0):
         hesap= "Çok İyi"
    if (toplam>6.0 and toplam<=12.0):
         hesap= "Güzel"
    if (toplam>12.0 and toplam<=18.0):
         hesap= "Orta"
    if (toplam>18.0 and toplam<=24.0):
         hesap= "Kötü"
    if (toplam>24.0 and toplam<=36.0):
         hesap= "Çok Kötü"
    if (toplam>36.0):
         hesap= "Ölümcül"
    
    return hesap

def kaliteHesabi(toplam):
    hesap= -1
    if (toplam>=0.0 and toplam<=6.0):
         hesap= 0
    if (toplam>6.0 and toplam<=12.0):
         hesap= 1
    if (toplam>12.0 and toplam<=18.0):
         hesap= 2
    if (toplam>18.0 and toplam<=24.0):
         hesap= 3
    if (toplam>24.0 and toplam<=36.0):
         hesap= 4
    if (toplam>36.0):
         hesap= 5
    
    return hesap



def yenidenHesap(toplam):
    hesap=0
    if toplam =="Çok İyi":
         hesap= 0
    if toplam == "Güzel":
         hesap= 1
    if toplam == "Orta":
         hesap= 2
    if toplam =="Kötü":
         hesap= 3
    if toplam == "Çok Kötü":
         hesap= 4
    if toplam == "Ölümcül":
         hesap= 5
    
    return hesap

def sonucBelirle(df):
  for _ in df["toplam"]:
      df["sonuc"] = df["toplam"].apply(kaliteHesabi)
  
  return df

veri_universite = pd.read_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_universite.xlsx")
veri_bursa = pd.read_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_bursa.xlsx")
veri_beyazid = pd.read_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_beyazid.xlsx")
veri_inegol = pd.read_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_inegol.xlsx")
veri_kestel = pd.read_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_kestel.xlsx")
veri_kulturpark = pd.read_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_kulturpark.xlsx")

# veri_universite = sonucBelirle(veri_universite)
# veri_bursa = sonucBelirle(veri_bursa)
# veri_beyazid = sonucBelirle(veri_beyazid)
# veri_inegol = sonucBelirle(veri_inegol)
# veri_kestel = sonucBelirle(veri_kestel)
# veri_kulturpark = sonucBelirle(veri_kulturpark)

# veri_beyazid.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_beyazid.xlsx")
# veri_bursa.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_bursa.xlsx")
# veri_inegol.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_inegol.xlsx")
# veri_kestel.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_kestel.xlsx")
# veri_kulturpark.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_kulturpark.xlsx")
# veri_universite.to_excel("/content/drive/My Drive/GuncelKonular/sonuclar2/data_universite.xlsx")



